interface=wlan0
bind-dynamic
port=0
dhcp-authoritative
dhcp-range=10.77.0.20,10.77.0.100,255.255.255.0,12h
dhcp-option=3,10.77.0.1
dhcp-option=6,10.77.0.1
dhcp-leasefile=/run/wiibridge-dnsmasq/dnsmasq.leases
no-resolv
log-dhcp
